name: Analyze Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clang
        run: sudo apt-get install -y clang

      - name: Install Clang-Tidy
        run: sudo apt-get install -y clang-tidy

      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      - name: Run Analyze Code Script
        run: bash ./analyze_code.sh