name: Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build and Run
        run: bash ./build_and_run.sh